//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogManagementTests.Dynamic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogManagementTests.Dynamic.Resources.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;TimeZone&quot;:{&quot;Id&quot;:&quot;China Standard Time&quot;,&quot;DisplayName&quot;:&quot;(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi&quot;,&quot;StandardName&quot;:&quot;China Standard Time&quot;,&quot;DaylightName&quot;:&quot;China Daylight Time&quot;,&quot;BaseUtcOffset&quot;:&quot;08:00:00&quot;,&quot;AdjustmentRules&quot;:null,&quot;SupportsDaylightSavingTime&quot;:false},&quot;Occurence&quot;:&quot;2017-02-10T10:41:29.2777014+08:00&quot;,&quot;User&quot;:&quot;sa&quot;,&quot;SessionId&quot;:&quot;abc&quot;,&quot;TransactionId&quot;:&quot;123&quot;,&quot;System&quot;:&quot;Security System&quot;,&quot;Application&quot;:&quot;Security Tester&quot;,&quot;Component&quot;:&quot;Authentication Component&quot;,&quot;Event&quot;:&quot;Validation&quot;,&quot;Priority&quot;:7,&quot;Status&quot;:2,&quot;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LogFormat {
            get {
                return ResourceManager.GetString("LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to param|a|param 1|true
        ///param|b|param 2|false
        ///param|c|param 3|true
        ///param|d|param 4|false
        ///
        ///literal|e|1
        ///literal|f|&quot;a&quot;
        ///literal|g|2.2
        ///literal|h|false
        ///
        ///param-test-data|param 1|1
        ///param-test-data|param 2|&quot;a&quot;
        ///param-test-data|param 3|2.2
        ///param-test-data|param 4|false
        ///
        ///id:TEST ID 123
        ///condition: ((a == e) &amp;&amp; (b==f)) &amp;&amp; ((c == g) &amp;&amp; (d == h))
        ///success:PREDEFINE_ACTION_1
        ///failure:PREDEFINE_ACTION_2
        ///
        ///.
        /// </summary>
        internal static string SourceCode1 {
            get {
                return ResourceManager.GetString("SourceCode1", resourceCulture);
            }
        }
    }
}
